// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AcumenTest.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("AcumenContactUs")]
    public partial class AcumenContactUsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "AcumenContactUs.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "AcumenContactUs", "In order to contact Acumen\r\nAs an end user\r\nI want to be able to find contact det" +
                    "ails of Acumen and get in touch to find out more", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Accurate Address")]
        public virtual void AccurateAddress()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Accurate Address", ((string[])(null)));
#line 7
 this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("I am on the Acumen home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
 testRunner.When("I navigate to the Contact Us page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "CompanyName",
                        "StreetAddress",
                        "Town",
                        "CountyWithPostCode",
                        "Country",
                        "ClientEnquiresTelephone",
                        "ClientEnquiresEmail",
                        "SupportEnquiresTelephone",
                        "SupportEnquiresEmail"});
            table1.AddRow(new string[] {
                        "Acumen Commercial Insights Ltd",
                        "26 George Street",
                        "Richmond upon Thames",
                        "Surrey TW9 1HY",
                        "UNITED KINGDOM",
                        "Tel: +44 (0)20 8334 0420",
                        "info@acumenci.com",
                        "Tel: +44 (0)20 8334 0430",
                        "support@acumenci.com"});
#line 10
 testRunner.Then("I should see an accurate address as follows", ((string)(null)), table1, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("ContactUs form successful submission Happy path")]
        public virtual void ContactUsFormSuccessfulSubmissionHappyPath()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ContactUs form successful submission Happy path", ((string[])(null)));
#line 15
 this.ScenarioSetup(scenarioInfo);
#line 16
 testRunner.Given("I am on the Acumen Contact Us page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Company",
                        "Location",
                        "Telephone",
                        "Email",
                        "Subject",
                        "YourMessage"});
            table2.AddRow(new string[] {
                        "SomeName",
                        "SomeCompany",
                        "London",
                        "",
                        "testKarunya@gmail.com",
                        "",
                        "Please contact me!"});
#line 17
 testRunner.When("I submit the contact form with the following details below", ((string)(null)), table2, "When ");
#line 20
 testRunner.Then("I should see successful submission message", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Required field Validation with EmailAddress only")]
        public virtual void RequiredFieldValidationWithEmailAddressOnly()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Required field Validation with EmailAddress only", ((string[])(null)));
#line 24
 this.ScenarioSetup(scenarioInfo);
#line 25
 testRunner.Given("I am on the Acumen Contact Us page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Company",
                        "Location",
                        "Telephone",
                        "Email",
                        "Subject",
                        "YourMessage"});
            table3.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "testKarunya@gmail.com",
                        "",
                        "Please contact me!"});
#line 26
 testRunner.When("I submit the contact form with the following details below", ((string)(null)), table3, "When ");
#line 29
 testRunner.Then("I should see errors about the other required fields that are not filled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Email format Validation for email with no domain name and atsign")]
        public virtual void EmailFormatValidationForEmailWithNoDomainNameAndAtsign()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Email format Validation for email with no domain name and atsign", ((string[])(null)));
#line 33
 this.ScenarioSetup(scenarioInfo);
#line 34
 testRunner.Given("I am on the Acumen Contact Us page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Company",
                        "Location",
                        "Telephone",
                        "Email",
                        "Subject",
                        "YourMessage"});
            table4.AddRow(new string[] {
                        "SomeName",
                        "SomeCompany",
                        "London",
                        "",
                        "testKarunya",
                        "",
                        "Please contact me!"});
#line 35
 testRunner.When("I submit the contact form with the following details below", ((string)(null)), table4, "When ");
#line 38
 testRunner.Then("I should see validation error message \'Email address seems invalid.\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Email format Validation for email with sometext and atSign but no domain")]
        public virtual void EmailFormatValidationForEmailWithSometextAndAtSignButNoDomain()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Email format Validation for email with sometext and atSign but no domain", ((string[])(null)));
#line 40
 this.ScenarioSetup(scenarioInfo);
#line 41
 testRunner.Given("I am on the Acumen Contact Us page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Company",
                        "Location",
                        "Telephone",
                        "Email",
                        "Subject",
                        "YourMessage"});
            table5.AddRow(new string[] {
                        "SomeName",
                        "SomeCompany",
                        "London",
                        "",
                        "testKarunya@",
                        "",
                        "Please contact me!"});
#line 42
 testRunner.When("I submit the contact form with the following details below", ((string)(null)), table5, "When ");
#line 45
 testRunner.Then("I should see validation error message \'Email address seems invalid.\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Email format Validation for email with sometext and atSign and domain with no dot" +
            "")]
        public virtual void EmailFormatValidationForEmailWithSometextAndAtSignAndDomainWithNoDot()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Email format Validation for email with sometext and atSign and domain with no dot" +
                    "", ((string[])(null)));
#line 47
 this.ScenarioSetup(scenarioInfo);
#line 48
 testRunner.Given("I am on the Acumen Contact Us page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Company",
                        "Location",
                        "Telephone",
                        "Email",
                        "Subject",
                        "YourMessage"});
            table6.AddRow(new string[] {
                        "SomeName",
                        "SomeCompany",
                        "London",
                        "",
                        "testKarunya@gmail",
                        "",
                        "Please contact me!"});
#line 49
 testRunner.When("I submit the contact form with the following details below", ((string)(null)), table6, "When ");
#line 52
 testRunner.Then("I should see validation error message \'Email address seems invalid.\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Email format Validation for email with notext after the dot")]
        public virtual void EmailFormatValidationForEmailWithNotextAfterTheDot()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Email format Validation for email with notext after the dot", ((string[])(null)));
#line 54
 this.ScenarioSetup(scenarioInfo);
#line 55
 testRunner.Given("I am on the Acumen Contact Us page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Company",
                        "Location",
                        "Telephone",
                        "Email",
                        "Subject",
                        "YourMessage"});
            table7.AddRow(new string[] {
                        "SomeName",
                        "SomeCompany",
                        "London",
                        "",
                        "testKarunya@gmail.",
                        "",
                        "Please contact me!"});
#line 56
 testRunner.When("I submit the contact form with the following details below", ((string)(null)), table7, "When ");
#line 59
 testRunner.Then("I should see validation error message \'Email address seems invalid.\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Email format success case")]
        public virtual void EmailFormatSuccessCase()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Email format success case", ((string[])(null)));
#line 61
 this.ScenarioSetup(scenarioInfo);
#line 62
 testRunner.Given("I am on the Acumen Contact Us page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Company",
                        "Location",
                        "Telephone",
                        "Email",
                        "Subject",
                        "YourMessage"});
            table8.AddRow(new string[] {
                        "",
                        "SomeCompany",
                        "London",
                        "",
                        "testKarunya@gmail.com",
                        "",
                        "Please contact me!"});
#line 63
 testRunner.When("I submit the contact form with the following details below", ((string)(null)), table8, "When ");
#line 66
 testRunner.Then("I should see no errors in the email field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Google map available")]
        public virtual void GoogleMapAvailable()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Google map available", ((string[])(null)));
#line 69
 this.ScenarioSetup(scenarioInfo);
#line 70
 testRunner.Given("I am on the Acumen Contact Us page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 71
 testRunner.Then("I should be able to see Google map widget showing address", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("How to find us is described")]
        public virtual void HowToFindUsIsDescribed()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("How to find us is described", ((string[])(null)));
#line 74
 this.ScenarioSetup(scenarioInfo);
#line 75
 testRunner.Given("I am on the Acumen Contact Us page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 76
 testRunner.Then("I should see how to find us section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
